services:
  postgres:
    image: postgres:15-alpine
    container_name: doel3d-postgres
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-doel3d}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - doel3d-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-doel3d}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Adminer for database administration
  # Uncomment if you prefer a web-based database UI over Prisma Studio
  # adminer:
  #   image: adminer:latest
  #   container_name: doel3d-adminer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - doel3d-network
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  doel3d-network:
    driver: bridge
